In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [8]:
df['job_posted_date_str'] = df['job_posted_date'].apply(lambda posted_date: posted_date.strftime('%Y-%m-%d'))

In [11]:
df[['job_posted_date', 'job_posted_date_str']]
type(df['job_posted_date_str'][0])

str

In [27]:
from datetime import datetime

current_date = datetime.now()

df['days_since_posted'] = df['job_posted_date'].apply(lambda date: (current_date - date).days)

In [28]:
df[['job_posted_date', 'days_since_posted']].head()

      job_posted_date  days_since_posted
0 2023-06-16 13:44:15                833
1 2023-01-14 13:18:07                986
2 2023-10-10 13:14:55                717
3 2023-07-04 13:01:41                815
4 2023-08-07 14:29:36                781

In [29]:
df_filtered = df[pd.notna(df['salary_year_avg'])].copy()

In [38]:
df_filtered['salary_category'] = df_filtered['salary_year_avg'].apply(lambda salary: 'Low' if salary < 60000 else ('High' if salary > 100000 else 'Medium'))

In [37]:
df_filtered[['salary_year_avg', 'salary_category']]

        salary_year_avg salary_category
28             109500.0            High
77             140000.0            High
92             120000.0            High
100            228222.0            High
109             89000.0          Medium
...                 ...             ...
785624         139216.0            High
785641         150000.0            High
785648         221875.0            High
785682         157500.0            High
785692         157500.0            High

[22003 rows x 2 columns]