In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [ ]:
df_drop_nan = df.copy()
df_drop_nan.dropna(subset='salary_year_avg', inplace=True)
df_drop_nan.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22003 entries, 28 to 785692
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        22003 non-null  object
 1   job_title              22003 non-null  object
 2   job_location           21723 non-null  object
 3   job_via                22003 non-null  object
 4   job_schedule_type      21987 non-null  object
 5   job_work_from_home     22003 non-null  bool
 6   search_location        22003 non-null  object
 7   job_posted_date        22003 non-null  datetime64[ns]
 8   job_no_degree_mention  22003 non-null  bool
 9   job_health_insurance   22003 non-null  bool
 10  job_country            22003 non-null  object
 11  salary_rate            22003 non-null  object
 12  salary_year_avg        22003 non-null  float64
 13  salary_hour_avg        0 non-null      float64
 14  company_name           22003 non-null  object
 15  job_skills             20170 non-null  object
 16  job_type_skills        20170 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 2.6+ MB

In [12]:
df_sample = df.copy()
df_sample.sample(frac=0.1).head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
182265,Software Engineer,"Senior Software Engineer, Java | Financial Ser...",Hong Kong,via Trabajo.org - Job Search - Jobs,Full-time,False,Hong Kong,2023-03-31 16:03:41,False,False,Hong Kong,None,NaN,NaN,Randstad Hong Kong,"['java', 'html', 'css', 'javascript', 'spring'...","{'libraries': ['spring'], 'programming': ['jav..."
414571,Data Engineer,Data Centre Engineer (On Demand model),"Millers Point NSW, Australia",via LinkedIn,Full-time,False,Australia,2023-06-08 16:41:45,False,False,Australia,None,NaN,NaN,DeRisk Technologies,None,None
582349,Software Engineer,Software Engineer,United Kingdom,via LinkedIn,Full-time,False,United Kingdom,2023-09-27 09:11:27,False,False,United Kingdom,None,NaN,NaN,Stanford Black Limited,"['python', 'react']","{'libraries': ['react'], 'programming': ['pyth..."
33510,Data Engineer,Big Data Engineer H/F,"Biot, France",via HelloWork,Full-time,False,France,2023-10-19 14:00:34,False,False,France,None,NaN,NaN,Abylsen,"['python', 'spark', 'hadoop']","{'libraries': ['spark', 'hadoop'], 'programmin..."
552381,Business Analyst,Hiring Data Analyst | Business Analyst,Anywhere,via LinkedIn,Full-time,True,India,2023-09-21 19:07:21,False,False,India,None,NaN,NaN,Ovidtech Technologies,"['python', 'word', 'powerpoint']","{'analyst_tools': ['word', 'powerpoint'], 'pro..."

In [13]:
df_filled = df.copy()
median_yearly_salary = df['salary_year_avg'].median()
df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_yearly_salary)
df_filled.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,115000.0,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,115000.0,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,115000.0,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,115000.0,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,115000.0,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."