In [44]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [45]:
df_us_jobs = df[df['job_country'] == 'United States'].copy()

In [46]:
df_us_jobs['job_posted_month'] = df_us_jobs['job_posted_date'].dt.to_period('M')

In [47]:
df_monthly_postings = df_us_jobs.groupby(by='job_posted_month').count()['job_title_short'].reset_index(name='postings_count')
df_monthly_postings

   job_posted_month  postings_count
0           2023-01           22670
1           2023-02           18020
2           2023-03           17904
3           2023-04           17282
4           2023-05           15283
5           2023-06           16694
6           2023-07           16210
7           2023-08           21029
8           2023-09           16313
9           2023-10           16998
10          2023-11           14736
11          2023-12           13153

In [48]:
df_us_merged = pd.merge(df_us_jobs, df_monthly_postings, how='right', on='job_posted_month')

In [49]:
df_us_merged.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month,postings_count
0,Data Engineer,Data Engineer,"Fort Worth, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-25 13:24:01,False,False,United States,None,NaN,NaN,Programmers.io,"['sql', 'python']","{'programming': ['sql', 'python']}",2023-01,22670
1,Data Engineer,Data Engineer,"San Mateo, CA",via LinkedIn,Full-time,False,"California, United States",2023-01-28 13:07:30,False,True,United States,None,NaN,NaN,Verkada,"['sql', 'python', 'aws', 'looker']","{'analyst_tools': ['looker'], 'cloud': ['aws']...",2023-01,22670
2,Business Analyst,Business Intelligence Intern,"Dallas, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-04 13:02:07,False,False,United States,None,NaN,NaN,Copart,"['r', 'python', 'sql', 'tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi'], 'pr...",2023-01,22670
3,Data Engineer,Data Engineer,"Cincinnati, OH",via SimplyHired,Full-time,False,"Texas, United States",2023-01-22 13:08:53,False,False,United States,None,NaN,NaN,Divisions Maintenance Group,"['sql', 'nosql', 'python', 'java', 'c++', 'sca...","{'databases': ['cassandra'], 'libraries': ['ha...",2023-01,22670
4,Data Analyst,Data Analyst,"Tampa, FL",via LinkedIn,Full-time,False,"Florida, United States",2023-01-19 13:19:45,False,False,United States,None,NaN,NaN,Citi,"['sql', 'python', 'unix', 'excel', 'jira']","{'analyst_tools': ['excel'], 'async': ['jira']...",2023-01,22670

In [65]:
df_not_remote_jobs = df[df['job_work_from_home'] == False].copy()
df_not_remote_salary = df_not_remote_jobs.groupby('job_title_short')['salary_year_avg'].mean().reset_index()
df_not_remote_salary.rename(columns={'salary_year_avg': 'salary_not_remote_avg'}, inplace=True)
df_not_remote_merged = pd.merge(df_not_remote_jobs, df_not_remote_salary, how='right', on='job_title_short')
df_not_remote_merged.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,salary_not_remote_avg
0,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,None,NaN,NaN,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow...",90177.41994
1,Business Analyst,Business Intelligence Intern,"Dallas, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-04 13:02:07,False,False,United States,None,NaN,NaN,Copart,"['r', 'python', 'sql', 'tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi'], 'pr...",90177.41994
2,Business Analyst,BI Engineer,Namibia,via Intellijobs.ai,Full-time,False,Namibia,2023-03-05 14:10:49,False,False,Namibia,None,NaN,NaN,Innover,"['sql', 'gcp', 'looker', 'tableau']","{'analyst_tools': ['looker', 'tableau'], 'clou...",90177.41994
3,Business Analyst,Business Analyst,"Tel Aviv-Yafo, Israel",via Comeet,Full-time,False,Israel,2023-09-05 13:50:12,False,False,Israel,None,NaN,NaN,ironSource,"['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['...",90177.41994
4,Business Analyst,Commercial Analyst,South Africa,via LinkedIn,Full-time,False,South Africa,2023-02-14 13:36:23,True,False,South Africa,None,NaN,NaN,PEP,"['sql', 'tableau', 'spss', 'sap']","{'analyst_tools': ['tableau', 'spss', 'sap'], ...",90177.41994

In [74]:
df_company_salary = df.groupby('company_name')['salary_year_avg'].mean().reset_index()
df_company_salary

                                       company_name  salary_year_avg
0                                           "Dbank"              NaN
1                                  "Hamkorbank" АТБ              NaN
2                                          "KELKOO"              NaN
3                               "PASHA Holding" LLC              NaN
4       "TECHNICUS LTD" sp. z o.o. ODDZIAŁ W POLSCE              NaN
...                                             ...              ...
139977  𝐏𝐓 𝐌𝐢𝐭𝐫𝐚 𝐏𝐢𝐧𝐚𝐬𝐭𝐡𝐢𝐤𝐚 𝐌𝐮𝐬𝐭𝐢𝐤𝐚 𝐑𝐞𝐧𝐭 (𝐌𝐏𝐌 𝐑𝐞𝐧𝐭)              NaN
139978                                🇮🇳 easyfix.in              NaN
139979                              🏛️WalletConnect              NaN
139980                                     💻 LGA IT              NaN
139981                       💾Data Trust Associates              NaN

[139982 rows x 2 columns]

In [72]:
df_company_remote = df[df['job_work_from_home'] == True].groupby('company_name').size().reset_index(name='remote_count')
df_company_remote

                                    company_name  remote_count
0                                    #EqualsTrue             4
1                                  #TeamGoHealth             1
2                        #twiceasnice Recruiting             1
3                                          &Work             1
4      (AEG) Application Engineering Group, Inc.             1
...                                          ...           ...
22983                                       知名外企             1
22984                                       精鼎医药             1
22985                     英屬維京群島商瑞嘉耐思科技有限公司台灣分公司             1
22986                                         雅虎             2
22987                                  𝐎𝐩𝐞𝐧𝐬𝐭𝐚𝐟𝐟             1

[22988 rows x 2 columns]

In [73]:
df_company_merged = pd.merge(df_company_salary, df_company_remote, how='inner', on='company_name')
df_company_merged

,company_name,salary_year_avg,remote_count
0,#EqualsTrue,NaN,4
1,#TeamGoHealth,NaN,1
2,#twiceasnice Recruiting,77750.0,1
3,&Work,NaN,1
4,"(AEG) Application Engineering Group, Inc.",NaN,1
...,...,...,...
22983,知名外企,NaN,1
22984,精鼎医药,NaN,1
22985,英屬維京群島商瑞嘉耐思科技有限公司台灣分公司,NaN,1
22986,雅虎,NaN,2
22987,𝐎𝐩𝐞𝐧𝐬𝐭𝐚𝐟𝐟,NaN,1